[server]
# host = 0.0.0.0  -> Allow all connections from any device in your network.
# host = 127.0.0.1 -> Allow connections from localhost only
# host = 192.168.1.50 -> Allow connections only to for this specific IP
host = 0.0.0.0

# Custom port for the web server.
# If the port 80 is being used by another service, you can change this here.
port = 80